### PR TITLE
Fixing overflow problems and better camp configuration

### PR DESCRIPTION
**Pull request by JohnieWalkerCZ**
## Changes
1. Fixed overflowing issue on smaller devices, improving mobile responsiveness.
2. Improved code formatting for better readability and maintainability.
3. Added a camp settings section to `_config.yaml` for centralized configuration.
4. Updated the template to use the newly defined `guide` property.
5. Refactored the codebase to utilize settings from `_config.yaml`, improving maintainability and configuration flexibility.

## Testing
- Verified responsive design on various device sizes
- Confirmed that the template correctly uses the new `guide` property
- Ensured all camp settings are properly pulled from `_config.yaml`

## Additional Notes
This update centralizes camp configuration in `_config.yaml`, making it easier to manage and update camp settings. It also improves the site's responsiveness on mobile devices.

Please review and let me know if any further changes are needed.

### CODE REVIEW

**Comment by JakubAndrysek** [comment]
nav_gallery_en.html
```html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top"><img style="max-width: 3.5rem" src="img/main_logo.png"></a>
        <a class="navbar-brand js-scroll-trigger" href="/">Robotic Camp</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/en">Introduction</a>
                </li>
                {% assign camps_list = site.camps | reverse %}
                {% for camp in camps_list limit: 5 %}
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#{{ camp.year }}">{{ camp.year }}</a>
                </li>
                {% endfor %}
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#contacts">Contacts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/gallery">CZ</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
```

nav_gallery_cz.html
```html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/"><img style="max-width: 3.5rem" src="img/main_logo.png"></a>
        <a class="navbar-brand js-scroll-trigger" href="/">Robotický tábor</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/">Úvod</a>
                </li>
                {% assign camps_list = site.camps | reverse %}
                {% for camp in camps_list limit: 5 %}
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#{{ camp.year }}">{{ camp.year }}</a>
                </li>
                {% endfor %}
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#contacts">Kontakty</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="/gallery-en">EN</a>
                </li> -->
            </ul>
        </div>
    </div>
</nav>
```

**Comment by JakubAndrysek** [comment]
Update camp source to folder _camps

Uprav tam ještě prosím tohle. Mě to nějak nejde

**Comment by JakubAndrysek** [comment]
Jinak je to suprový 😍

**Comment by JohnieWalkerCZ** [comment]
Added the requested changes.

**Pull request merged**
